quarkus.http.port=8082
quarkus.application.name=document-caching
quarkus.redis.hosts=redis://localhost:6379
quarkus.grpc.server.use-separate-server=false
quarkus.grpc.server.plain-text=true

quarkus.container-image.build=true
quarkus.container-image.name=document-caching
quarkus.container-image.group=sagargrovetech

consul.host=localhost
consul.port=8500